.TH man 1 "20 April 2020" "0.2.0" "tak man page"

.SH NAME
tak \- Create presentations that use the Takahashi method.

.SH SYNOPSIS
tak [OPTIONS]... [INPUT] [OUTPUT]

.SH DESCRIPTION
The tak command takes as INPUT a YAML file that specifies the presentation and outputs the presentation in the required format into the file OUTPUT.

.TP
\fB -t TEMPLATE, --template TEMPLATE \fR
The jinja2 template to use for output (See TEMPLATES).

.TP
\fB -n, --no-escape \fR
Disable sanitizing content for html. By default, tak assumes that the output is in html format and sanitizes content using html character entities. For example the text slide,

    # <html>

is written to the output as

    &lt;html&gt;

.SH SYNTAX
The top-level value is a dictionary. The keys 'title' and 'author' specifies the title and author. The 'slides' key is a sequence of slides.

Each slide is a text slide or an image slide.

    text: The content goes here.

    image:
      caption: The caption here.
      file: path to the image here.

.SH TEMPLATES
If a template file is given as argument using the \fB -t \fR option, tak searches or it in the current directory and then in the list of builtin templates.

The following templates are distributed with tak.

.TP
\fB dark.html \fR
White text on black background (default). 

.TP
\fB light.html \fR
Black text on white background.

.SH BUGS
No known bugs.

.SH AUTHOR
Balagopal Komarath <bkomarath@rbgo.in>
